### PR TITLE
Better error messages when PY_PYTHON* is malformed

### LINKED ISSUE #108: Make sure that setting `PY_PYTHON` to an invalid value is somehow discoverable
Either directly error out or shown in the error logging.

### PR DESCRIPTION
**Pull request by brettcannon**
Closes #108

For `PY_PYTHON3="3.8.10"` without `PYLAUNCH_DEBUG`:
```
Error parsing '8.10' as an integer: invalid digit found in string
```

With `PYLAUNCH_DEBUG`:
```
Checking the PY_PYTHON3 environment variable
PY_PYTHON3 = '3.8.10'
Error parsing '8.10' as an integer: invalid digit found in string
```

### CODE REVIEW

**Comment by brettcannon** [comment]
The coverage failures are false-positives.

**Comment by jefftriplett** [comment]
Would this show up in verbose (`-v`) mode too?

**Comment by brettcannon** [comment]
> Would this show up in verbose (-v) mode too?

No, that's passed directly to Python and I don't want to inject the  Python Launcher into that as people parse that output.

**Comment by jefftriplett** [comment]
That makes sense. I guess I rarely if ever run `python -v`. I think the error message is much clearer about what is going on. It's much easier to solve a problem when it's obvious why something is failing. 👍🏼

**Pull request merged**
